"""update password reset model

Revision ID: 3d62d5ac11d2
Revises: da57e09a60ff
Create Date: 2025-05-06 15:10:12.065929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3d62d5ac11d2'
down_revision: Union[str, None] = 'da57e09a60ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('password_resets', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('password_resets', 'token',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    #op.drop_index('password_reset_token', table_name='users')
    #op.drop_index('verification_token', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.create_index('verification_token', 'users', ['verification_token'], unique=True)
    #op.create_index('password_reset_token', 'users', ['password_reset_token'], unique=True)
    op.alter_column('password_resets', 'token',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('password_resets', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
